#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5
umask 077

# This wizard persists only the non-secret private-key path in owner-only local
# state. The only repository output is the reviewed public allowed_signers line.
SCRIPT_PATH=$(readlink -f -- "${BASH_SOURCE[0]}")
SOURCE_REPO="${SOURCE_REPO:-$(dirname -- "$(dirname -- "$SCRIPT_PATH")")}"
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/ssh-mixer-maintainer"
[[ ! -L "$STATE_DIR" ]] || { printf 'Unsafe state-directory symlink: %s\n' "$STATE_DIR" >&2; exit 1; }
mkdir -p -- "$STATE_DIR"
chmod 700 -- "$STATE_DIR"
ENV_FILE="$STATE_DIR/release-signing.conf"
[[ ! -L "$ENV_FILE" ]] || { printf 'Unsafe state-file symlink: %s\n' "$ENV_FILE" >&2; exit 1; }
touch "$ENV_FILE"
[[ -f "$ENV_FILE" ]] || { printf 'State path is not a regular file: %s\n' "$ENV_FILE" >&2; exit 1; }
chmod 600 "$ENV_FILE"
TRUST_ROOT="$SOURCE_REPO/release/allowed_signers"
KEY_PATH=""
PUBLIC_KEY=""
FINGERPRINT=""
ROUNDTRIP_DIR=""

cleanup_roundtrip() {
  if [[ -n "$ROUNDTRIP_DIR" && -d "$ROUNDTRIP_DIR" ]]; then
    rm -rf -- "$ROUNDTRIP_DIR"
  fi
}
trap cleanup_roundtrip EXIT HUP INT TERM

fail() {
  printf '  %s✗ %s%s\n' "$RED" "$1" "$RESET" >&2
  exit 1
}

banner "SSH-mixer production release signing"

stage "Choose dedicated offline key storage"
say "The private key stays outside Git, GitHub Actions, and the SSH-mixer repository."
say "Use an encrypted local volume or removable storage reserved for release signing."
warn "Do not use a Managed Identity, login key, contributor key, or CI key."
if [[ -n "${APPROVED_RELEASE_SIGNING_KEY_PATH:-}" ]]; then
  KEY_PATH="$APPROVED_RELEASE_SIGNING_KEY_PATH"
  say "Using the encrypted signing-drive location already approved by the storage wizard."
else
  step "Enter a new or existing absolute path for the dedicated Ed25519 private key."
  ask RELEASE_SIGNING_KEY_PATH "Private-key path (outside the repository):"
  KEY_PATH="$RELEASE_SIGNING_KEY_PATH"
fi
[[ "$KEY_PATH" != *$'\n'* ]] || fail "the private-key path must not contain a newline"
[[ "$KEY_PATH" = /* ]] || fail "the private-key path must be absolute"
KEY_PATH=$(realpath -m -- "$KEY_PATH")
SOURCE_REPO=$(realpath -e -- "$SOURCE_REPO")
case "$KEY_PATH/" in
  "$SOURCE_REPO/"*) fail "the private key must not be inside the SSH-mixer repository" ;;
esac
case "$KEY_PATH" in
  *.pub) fail "enter the private-key path, not its .pub path" ;;
esac
[[ ! -L "$KEY_PATH" && ! -L "$KEY_PATH.pub" ]] || fail "release key paths must not be symbolic links"
mkdir -p -- "$(dirname -- "$KEY_PATH")"
if [[ -e "$KEY_PATH" ]]; then
  [[ -f "$KEY_PATH" && -f "$KEY_PATH.pub" ]] || fail "an existing key requires regular private and .pub files"
  chmod 600 -- "$KEY_PATH"
  chmod 644 -- "$KEY_PATH.pub"
  if ssh-keygen -y -P '' -f "$KEY_PATH" >/dev/null 2>&1; then
    warn "The unfinished key from the previous attempt has an empty passphrase and cannot become the production signer."
    [[ ! -e "$TRUST_ROOT" ]] || fail "the unencrypted key is already referenced by a trust root; separate rotation review is required"
    confirm "Delete only this unapproved key pair and generate an encrypted replacement?" \
      || fail "unencrypted key replacement was not approved"
    rm -f -- "$KEY_PATH" "$KEY_PATH.pub"
  else
    say "Existing encrypted key found; no key bytes will be replaced."
  fi
fi
if [[ ! -e "$KEY_PATH" ]]; then
  confirm "Generate a new encrypted Ed25519 release key on the approved signing drive?" \
    || fail "key generation was not approved"
  warn "When ssh-keygen asks for a passphrase, do not leave it empty."
  note "Use a strong unique passphrase; it goes directly to ssh-keygen and is never stored."
  ssh-keygen -t ed25519 -a 100 -f "$KEY_PATH" -C "ssh-mixer production release signing"
fi
chmod 600 -- "$KEY_PATH"
chmod 644 -- "$KEY_PATH.pub"
if ssh-keygen -y -P '' -f "$KEY_PATH" >/dev/null 2>&1; then
  fail "the new key still has an empty passphrase; rerun setup to approve its replacement"
fi
note "Enter the key passphrase once so ssh-keygen can prove the public/private pair matches."
derived_public=$(ssh-keygen -y -f "$KEY_PATH" | awk 'NF >= 2 { print $1 " " $2; exit }')
file_public=$(awk 'NF >= 2 { print $1 " " $2; exit }' "$KEY_PATH.pub")
[[ "$derived_public" = "$file_public" ]] || fail "the private key and .pub file do not match"
write_env RELEASE_SIGNING_KEY_PATH "$KEY_PATH"
chmod 600 "$ENV_FILE"
say "The encrypted private key passed format, permissions, and pair checks."
note "Only its non-secret path was remembered in owner-only local state."
pause "Continue to fingerprint review?"

stage "Review the public fingerprint"
PUBLIC_KEY=$(awk 'NF >= 2 { print $1 " " $2; exit }' "$KEY_PATH.pub")
[[ "$PUBLIC_KEY" = ssh-ed25519\ * ]] || fail "the release public key is not Ed25519"
fingerprint_line=$(ssh-keygen -lf "$KEY_PATH.pub" -E sha256)
FINGERPRINT=$(awk '{print $2}' <<<"$fingerprint_line")
say "Candidate production signer:"
printf '  %s\n' "$fingerprint_line"
say "The wizard already proved that the encrypted private key and this public key match."
warn "Review the displayed fingerprint; a separate repository check will verify it again before release."
confirm "Approve this exact public fingerprint as the proposed production signer?" \
  || fail "production signer fingerprint was not approved"
say "Fingerprint approved."
pause "Continue to the public trust-root proposal?"

stage "Approve and write only the public trust root"
ALLOWED_SIGNER="ssh-mixer-release namespaces=\"ssh-mixer-release\" $PUBLIC_KEY"
say "This is the complete public line proposed for release/allowed_signers:"
printf '  %s\n' "$ALLOWED_SIGNER"
say "It grants this key only the ssh-mixer-release signing namespace."
warn "Writing it enables trust only in source; it does not sign, install, tag, push, or publish anything."
confirm "Write this exact public line to $TRUST_ROOT?" \
  || fail "trust-root write was not approved"
[[ ! -L "$TRUST_ROOT" ]] || fail "the trust-root path must not be a symbolic link"
if [[ -e "$TRUST_ROOT" ]]; then
  [[ -f "$TRUST_ROOT" ]] || fail "the trust-root path is not a regular file"
  existing=$(cat -- "$TRUST_ROOT")
  [[ "$existing" = "$ALLOWED_SIGNER" ]] \
    || fail "a different production trust root already exists; rotation requires separate review"
  say "The identical public trust root already exists; nothing was replaced."
else
  trust_tmp=$(mktemp "$SOURCE_REPO/release/.allowed_signers.XXXXXX")
  chmod 644 -- "$trust_tmp"
  printf '%s\n' "$ALLOWED_SIGNER" > "$trust_tmp"
  mv -- "$trust_tmp" "$TRUST_ROOT"
  say "Wrote the approved public trust root atomically."
fi
pause "Continue to a temporary signature round-trip?"

stage "Verify an OpenSSH signature round-trip"
ROUNDTRIP_DIR=$(mktemp -d)
chmod 700 -- "$ROUNDTRIP_DIR"
printf 'ssh-mixer release signer verification\nprincipal=ssh-mixer-release\nnamespace=ssh-mixer-release\nfingerprint=%s\n' \
  "$FINGERPRINT" > "$ROUNDTRIP_DIR/statement.txt"
chmod 600 -- "$ROUNDTRIP_DIR/statement.txt"
note "ssh-keygen will ask for the passphrase directly and create only a temporary test signature."
ssh-keygen -Y sign -f "$KEY_PATH" -n ssh-mixer-release "$ROUNDTRIP_DIR/statement.txt"
ssh-keygen -Y verify \
  -f "$TRUST_ROOT" \
  -I ssh-mixer-release \
  -n ssh-mixer-release \
  -s "$ROUNDTRIP_DIR/statement.txt.sig" \
  < "$ROUNDTRIP_DIR/statement.txt"
rm -rf -- "$ROUNDTRIP_DIR"
ROUNDTRIP_DIR=""
say "The approved public trust root verified the temporary signature."
say "The temporary statement and signature were removed."
pause "Continue to secure-storage handoff?"

stage "Secure the key and return for review"
say "No Git configuration, tag, metadata signature, push, release, or publication was performed."
step "Close or unmount the private-key storage when it is not needed."
step "Record the fingerprint in your private release record, never in an issue or diagnostic bundle."
printf '  Fingerprint: %s\n' "$FINGERPRINT"
step "Return to the coding agent so it can review the public trust-root diff and regenerate the clean candidate."
warn "Do not run the release or attestation workflow yet. Those remain separate approvals."
confirm "Is the signing key now secured for offline storage?" \
  || fail "secure-storage handoff is incomplete"

finish
